# Generated by Django 5.2.5 on 2026-06-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('mileage', models.PositiveIntegerField()),
                ('fuel', models.CharField(max_length=100)),
                ('transmission', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('horsepower', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(upload_to='cars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
