# Generated by Django 5.2.5 on 2026-08-25 08:01

import cars.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='cover_image',
            field=models.ImageField(upload_to='cars/', validators=[cars.validator.validate_IMG_file]),
        ),
    ]
